version: "3.8"

volumes:
  postgres:
    driver: local

services:
  postgres:
    restart: unless-stopped
    image: postgres:12
    container_name: bpdwatch-${FLASK_ENV}-postgres
    environment:
      POSTGRES_USER: bpdwatch
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: bpdwatch
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./backup:/backups
    ports:
      - "5432:5432"

  web:
    restart: unless-stopped
    container_name: bpdwatch-${FLASK_ENV}-web
    build:
        context: .
        args:
        - DOCKER_BUILD_ENV
        dockerfile: ./dockerfiles/web/Dockerfile
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_DEFAULT_REGION: us-east-1
      MINIO_URL: ${MINIO_URL}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      APPROVE_REGISTRATIONS: ""
      DISABLE_REGISTRATION: ""
      FLASK_APP: app
      FLASK_ENV: ${FLASK_ENV}
      SQLALCHEMY_DATABASE_URI: "${SQLALCHEMY_DATABASE_URI}"
      SECRET_KEY: "${SECRET_KEY}"
      RECAPTCHA_V3_SITE_KEY: "${RECAPTCHA_V3_SITE_KEY}"
      RECAPTCHA_V3_SECRET_KEY: "${RECAPTCHA_V3_SECRET_KEY}"
      RECAPTCHA_V3_THRESHOLD: "0.5"
      MAIL_SERVER: ${MAIL_SERVER}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: "${MAIL_PASSWORD}"
      OO_MAIL_SUBJECT_PREFIX: "[BPD Watch]"
      OO_MAIL_SENDER: "BPD Watch <info@bpdwatch.com>"
    volumes:
      - ./OpenOversight/:/usr/src/app/OpenOversight/:z
    user: "1000"
    links:
      - postgres:postgres
    expose:
      - "3000"
    command: scripts/entrypoint.sh
    ports:
      - "3000:3000"
