"""Add do_not_call flag to Officer model

Revision ID: 38cd53bc3061
Revises: c5bc94be5b08
Create Date: 2021-10-26 12:44:55.962708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38cd53bc3061'
down_revision = 'c5bc94be5b08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('officers', sa.Column('do_not_call', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('officers', 'do_not_call')
    # ### end Alembic commands ###
