"""Add unique constraints to assigments and salaries

Revision ID: 3c2e14adcd0d
Revises: 38cd53bc3061
Create Date: 2021-11-26 17:48:25.081788

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = '3c2e14adcd0d'
down_revision = '38cd53bc3061'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_assignments_per_officer', 'assignments', ['officer_id', 'job_id', 'star_date', 'resign_date'])
    op.create_unique_constraint('unique_salaries_per_officer_per_year', 'salaries', ['officer_id', 'year'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_salaries_per_officer_per_year', 'salaries', type_='unique')
    op.drop_constraint('unique_assignments_per_officer', 'assignments', type_='unique')
    # ### end Alembic commands ###
