"""change officer.do_not_call to officer.sao_list

Revision ID: 452c591d3968
Revises: 567cbd09e202
Create Date: 2022-05-26 15:22:41.274255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '452c591d3968'
down_revision = '567cbd09e202'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('officers', sa.Column('sao_list', sa.String(), nullable=True))
    op.create_index(op.f('ix_officers_sao_list'), 'officers', ['sao_list'], unique=False)
    op.execute("update officers set sao_list = 'Do Not Call' where do_not_call = true and department_id = 1")
    op.drop_column('officers', 'do_not_call')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('officers', sa.Column('do_not_call', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.execute("update officers set do_not_call = true where sao_list = 'Do Not Call'")
    op.drop_index(op.f('ix_officers_sao_list'), table_name='officers')
    op.drop_column('officers', 'sao_list')
    # ### end Alembic commands ###
