"""Modify assignment unique constraint

Revision ID: 567cbd09e202
Revises: 5e1416d2b55a
Create Date: 2021-11-28 10:55:34.151410

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = '567cbd09e202'
down_revision = '5e1416d2b55a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_assignments_per_officer', 'assignments', type_='unique')
    op.create_unique_constraint('unique_assignments_per_officer', 'assignments', ['officer_id', 'job_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_assignments_per_officer', 'assignments', type_='unique')
    op.create_unique_constraint('unique_assignments_per_officer', 'assignments', ['officer_id', 'job_id', 'star_date', 'resign_date'])
    # ### end Alembic commands ###
