"""Add officer age

Revision ID: 5e1416d2b55a
Revises: 3c2e14adcd0d
Create Date: 2021-11-26 18:11:16.406038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e1416d2b55a'
down_revision = '3c2e14adcd0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('officers', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('officers', 'age')
    # ### end Alembic commands ###
